const fs = require('fs');
const path = require('path');
const { isInvalidNumber, isHttpUrl, TRUSTED_TYPES, TRUSTED_CONFIDENCE } = require('./data_rules');
const root = path.join(__dirname, '..');
const read = (p) => { const full = path.join(root, p); if (!fs.existsSync(full)) return []; const j=JSON.parse(fs.readFileSync(full,'utf8')); return Array.isArray(j)?j:(Array.isArray(j.records)?j.records:[]); };
const collected = read('data/collected_mexico_numbers.json');
const signals = read('data/crowd_signal_mexico_numbers.json');
const ios = read('data/ios_numbers.json');
const catalog = read('data/source_catalog_mexico.json');
const runLogPath = path.join(root,'data/collector_run_log.json');
const runLog = fs.existsSync(runLogPath) ? JSON.parse(fs.readFileSync(runLogPath,'utf8')) : { sources:[] };
const today = new Date().toISOString().slice(0,10);
const trusted = collected.filter((r)=> TRUSTED_TYPES.has(String(r.type||'').toLowerCase()) && TRUSTED_CONFIDENCE.has(String(r.confidence||'').toLowerCase()) && ['scam','suspicious'].includes(String(r.tag||'').toLowerCase()) && isHttpUrl(r.sourceUrl) && !isInvalidNumber(String(r.normalizedNumber||'')));
const officialCount = trusted.filter((r)=>['official','government','police'].includes(String(r.type||'').toLowerCase())).length;
const mediaCount = trusted.filter((r)=>String(r.type||'').toLowerCase()==='media').length;
const todayAddedCount = trusted.filter((r)=> String(r.updatedAt||r.collectedAt||'').startsWith(today)).length;
const succ = (runLog.sources||[]).filter((s)=>(s.accepted||0)>0).length;
const fail = (runLog.sources||[]).filter((s)=>(s.accepted||0)===0 && (s.errors||[]).length>0).length;
const bySource = {};
for (const r of trusted) bySource[r.source] = (bySource[r.source]||0)+1;
const topSources = Object.entries(bySource).sort((a,b)=>b[1]-a[1]).slice(0,5).map(([source,count])=>({source,count}));
const output = { generatedAt:new Date().toISOString(), officialCount, mediaCount, signalCount:signals.length, totalTrustedCount:trusted.length, todayAddedCount, iosExportCount:ios.length, sourceCount:catalog.length, sourceSuccessCount:succ, sourceFailedCount:fail, lastCollectorStatus:runLog.lastCollectorStatus || 'partial', topSources };
fs.writeFileSync(path.join(root,'data/public_stats.json'), JSON.stringify(output,null,2)+'\n');
console.log(`Generated public stats. trusted=${trusted.length}`);
