#!/usr/bin/env node
const fs=require('fs');const path=require('path');
const ROOT=process.cwd(),CSV=path.join(ROOT,'data','community_bulk_import_numbers.csv'),PENDING=path.join(ROOT,'data','pending_numbers.json'),SCAM=path.join(ROOT,'scam_numbers.json'),REPORT=path.join(ROOT,'data','community_bulk_import_report.json');
const cats=new Set(['spam','telemarketing','cobranza','publicidad','robocall','scam','fraud','extortion','unknown']);
const parse=l=>{const o=[];let c='',q=false;for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='"'){if(q&&l[i+1]==='"'){c+='"';i++;}else q=!q;}else if(ch===','&&!q){o.push(c);c='';}else c+=ch;}o.push(c);return o;};
const norm=r=>{const d=String(r||'').replace(/\D/g,'');if(d.length===10)return '+52'+d;if(d.length===12&&d.startsWith('52'))return '+'+d;return null;};
const now=new Date().toISOString();const pending=fs.existsSync(PENDING)?JSON.parse(fs.readFileSync(PENDING,'utf8')):[];const scam=new Set(JSON.parse(fs.readFileSync(SCAM,'utf8')).map(x=>x.number));
const map=new Map(pending.map(x=>[x.number,x]));const report={importedAt:now,categoryBreakdown:{},addedToPending:0,updatedExistingPending:0,skippedReasonsSummary:{}};const skip=k=>report.skippedReasonsSummary[k]=(report.skippedReasonsSummary[k]||0)+1;
const lines=fs.existsSync(CSV)?fs.readFileSync(CSV,'utf8').split(/\r?\n/).filter(Boolean):[];for(let i=1;i<lines.length;i++){const c=parse(lines[i]);if(c.length<7){skip('invalid_row');continue;}const n=norm(c[0]);if(!n){skip('invalid_number');continue;}if(scam.has(n)){skip('already_in_official_db');continue;}const category=cats.has(String(c[7]||'spam').toLowerCase())?String(c[7]||'spam').toLowerCase():'spam';report.categoryBreakdown[category]=(report.categoryBreakdown[category]||0)+1;const conf=Math.min(0.85,Math.max(0,Number(c[6]||0.35)||0.35));const src={sourceName:c[2]||'Community source',sourceType:'community_report',sourceUrl:c[3]||'',confidence:conf,mode:'community_bulk_csv_import',collectedAt:now};if(!map.has(n)){map.set(n,{number:n,label:'suspicious',country:'MX',category,sourceType:'community_report',sourceName:src.sourceName,sourceUrl:src.sourceUrl,region:c[4]||'México',confidence:conf,status:'pending_review',evidenceCount:1,sources:[src],firstSeenAt:now,updatedAt:now,note:c[5]||''});report.addedToPending++;} else {const ex=map.get(n);const srcMap=new Map((ex.sources||[]).map(s=>[`${s.sourceName}||${s.sourceUrl}`,s]));srcMap.set(`${src.sourceName}||${src.sourceUrl}`,src);ex.sources=[...srcMap.values()];ex.evidenceCount=ex.sources.length;ex.confidence=Math.min(0.85,Math.max(Number(ex.confidence)||0,conf));ex.category=cats.has(String(ex.category||'').toLowerCase())?ex.category:category;ex.updatedAt=now;map.set(n,ex);report.updatedExistingPending++;}}
const out=[...map.values()].sort((a,b)=>a.number.localeCompare(b.number));fs.writeFileSync(PENDING,JSON.stringify(out,null,2)+'\n');report.pendingAfter=out.length;fs.writeFileSync(REPORT,JSON.stringify(report,null,2)+'\n');
