#!/usr/bin/env node
const fs=require('fs');const path=require('path');const https=require('https');
(async()=>{const ROOT=process.cwd(),CSV=path.join(ROOT,'data','community_bulk_import_numbers.csv'),PENDING=path.join(ROOT,'data','pending_numbers.json'),SCAM=path.join(ROOT,'scam_numbers.json'),SNAP=path.join(ROOT,'data','community_source_snapshots','community_signals_snapshot.csv'),REPORT=path.join(ROOT,'data','community_bulk_refresh_report.json');
const HEADER='number,label,sourceName,sourceUrl,region,note,confidence,category',ua='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36';
const SOURCES=[['https://www.telefonospam.com.mx/top-spam','TelefonoSpam MX'],['https://www.tellows.mx/num/%2B52','Tellows MX']];
const parse=l=>{const o=[];let c='',q=false;for(let i=0;i<l.length;i++){const ch=l[i];if(ch==='"'){if(q&&l[i+1]==='"'){c+='"';i++;}else q=!q;}else if(ch===','&&!q){o.push(c);c='';}else c+=ch;}o.push(c);return o;};
const toLine=r=>r.map(v=>{const t=String(v??'');return /[",\n]/.test(t)?`"${t.replace(/"/g,'""')}"`:t;}).join(',');
const norm=x=>{const d=String(x||'').replace(/\D/g,'');let l='';if(d.length===10)l=d;else if(d.length===12&&d.startsWith('52'))l=d.slice(2);else return null; if(!/^\d{10}$/.test(l)||l.startsWith('800'))return null; return '+52'+l;};
const infer=t=>{const s=t.toLowerCase(); if(/fraude|estafa|phishing/.test(s))return 'fraud'; if(/extorsi/.test(s))return 'extortion'; if(/robot|automática|automatica/.test(s))return 'robocall'; if(/cobranza|deuda|banco|crédito|credito/.test(s))return 'cobranza'; if(/telemarketing|ventas/.test(s))return 'telemarketing'; if(/publicidad/.test(s))return 'publicidad'; if(/spam|molestia|no deseado/.test(s))return 'spam'; return 'unknown';};
const fetchRetry=(url,attempt=1)=>new Promise((res,rej)=>{const req=https.get(url,{timeout:20000,headers:{'User-Agent':ua,'Accept-Language':'es-MX,es;q=0.9,en;q=0.8'}},r=>{if((r.statusCode||0)>=400){r.resume();return rej(new Error('HTTP '+r.statusCode));}let d='';r.on('data',c=>d+=c);r.on('end',()=>res(d));});req.on('timeout',()=>req.destroy(new Error('timeout')));req.on('error',e=>attempt<3?setTimeout(()=>fetchRetry(url,attempt+1).then(res).catch(rej),300*attempt):rej(e));});
const report={refreshedAt:new Date().toISOString(),usedFallbackSnapshot:false,fallbackSnapshotRows:0,fallbackSnapshotAddedToCsv:0,dnsFailures:0,retryAttempts:0,categoryBreakdown:{},sources:[]};
const scamSet=new Set((JSON.parse(fs.readFileSync(SCAM,'utf8'))||[]).map(x=>x.number)); const pendingSet=new Set((fs.existsSync(PENDING)?JSON.parse(fs.readFileSync(PENDING,'utf8')):[]).map(x=>x.number));
let rows=[];if(fs.existsSync(CSV)){const l=fs.readFileSync(CSV,'utf8').split(/\r?\n/).filter(Boolean);for(let i=1;i<l.length;i++){const c=parse(l[i]);if(c.length<7)continue;rows.push(c.length>=8?c:[c[0],c[1],c[2],c[3],c[4],c[5],c[6],'spam']);}}
const seen=new Set(rows.map(r=>norm(r[0])).filter(Boolean));
for(const [url,name] of SOURCES){const sr={name,url,fetchOk:false,added:0,error:null};try{const html=await fetchRetry(url);sr.fetchOk=true;const m=html.match(/\+?\d[\d\s()\-]{7,20}\d|\b\d{10,12}\b/g)||[];for(const c of m){const n=norm(c);if(!n||seen.has(n)||scamSet.has(n)||pendingSet.has(n))continue;const i=html.indexOf(c),cat=infer(html.slice(Math.max(0,i-120),i+120));report.categoryBreakdown[cat]=(report.categoryBreakdown[cat]||0)+1;rows.push([n,'suspicious',name,url,'México','Reporte comunitario',cat==='spam'?0.45:0.35,cat]);seen.add(n);sr.added++;}}catch(e){if(String(e.message).includes('EAI_AGAIN'))report.dnsFailures++; report.retryAttempts+=2; sr.error=e.message;}report.sources.push(sr);}
if(report.sources.every(s=>!s.fetchOk)&&fs.existsSync(SNAP)){report.usedFallbackSnapshot=true;const l=fs.readFileSync(SNAP,'utf8').split(/\r?\n/).filter(Boolean);report.fallbackSnapshotRows=Math.max(0,l.length-1);for(let i=1;i<l.length;i++){const c=parse(l[i]),n=norm(c[0]);if(!n||seen.has(n)||scamSet.has(n)||pendingSet.has(n))continue;rows.push(c.length>=8?c:[c[0],c[1],c[2],c[3],c[4],c[5],c[6],'spam']);seen.add(n);report.fallbackSnapshotAddedToCsv++;}}
fs.writeFileSync(CSV,HEADER+'\n'+rows.map(toLine).join('\n')+'\n');fs.writeFileSync(REPORT,JSON.stringify(report,null,2)+'\n');
})();
